- name: Create directory for website
  file: 
    path: /www
    state: directory

- name: Clone project from repository
  git:
    repo: https://github.com/qqwerty222/python-project.git
    dest: /www/
    